name: Continuous Integration

on: pull_request

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'
    - run: yarn test
  check-oss:
    name: Check Open Source compliance
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'
    - run: yarn oss
    - run: git diff --exit-code && git diff --cached --exit-code || (echo "Please run 'yarn oss' and commit the result." && exit 1)
