name: Publish package on GitHub
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: "yarn config set --json npmScopes '{\"datadog\": {\"npmRegistryServer\": \"https://npm.pkg.github.com\", \"npmAuthToken\": \"'$YARN_NPM_AUTH_TOKEN'\"}}'"
      env:
        YARN_NPM_AUTH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
    - run: yarn
    - run: yarn npm publish
